title:             OSCAR
email:             chief@rubis.snu.ac.kr
description:       Open-Source Self-Driving CAR
author:            Real-Time Ubiquitous Systems Laboratory, Seoul National University
url:               "https://rubis-lab.github.io/oscar-pages"

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
