title:             OSCAR
email:             lab@rubis.snu.ac.kr
description:       Open-Source Self-Driving CAR
author:            RUBIS
baseurl:           "/oscar-pages"
url:               "https://alkaza.github.io"

# Social Profiles
github_username:   rubis-lab

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
